data:
  root_dir: ""
  img: "rgb"
  iris: "irismask2"
  eye: "eyemask2"
  camera: "sparse/0"
  select: []
  split: -1
  env: "lights/limpopo_golf_course_2k.png"
  load_img: True
model:
  dir: "./model"
render:
  cornea_alpha: 0.2
optim:
  init_gaze: [0, 0]
  init_tohead: [3.1415926, 0, 0]
  init_translate: "sparse_points_interest.ply"
  init_scale: 0.5
  init_npz: -1
  batch: 1
  max_iter: [-1, 10, 10]
  log_interval: 1
  imgsave_interval: 20
  display_res_ratio: 1
  lr_base: 0.01
  lr_ramp: 0.1
device: "cuda"
